# .readthedocs.yaml
# Read the Docs configuration file for wamp-xbr
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  # Required for sphinxcontrib-soliditydomain submodule
  submodules:
    include: all

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

python:
  install:
    # Install the package with dev dependencies (includes docs tools)
    - method: pip
      path: .
      extra_requirements:
        - dev
